angular.module("directives",[])
    .directive("menu",function(){
        return{
            restrict:"EA",
            templateUrl:"demon.html",
            transclude:true,
            scope:{},
            link:function($scope,b,c){
                $scope.data=[
                    {
                        name:"111",
                        son:[
                            {name:"1-1"},
                            {name:"1-2"},
                            {name:"1-3"}
                        ]
                    },
                    {
                        name:"222",
                        son:[
                            {name:"2-1"},
                            {name:"2-2"},
                            {name:"2-3"}
                        ]
                    },
                    {
                        name:"333",
                        son:[
                            {name:"3-1"},
                            {name:"3-2"},
                            {name:"3-3"}
                        ]
                    },
                    {
                        name:"444",
                        son:[
                            {name:"4-1"},
                            {name:"4-2"},
                            {name:"4-3"}
                        ]
                    }
                ]
                $scope.a=0;
                $scope.change=function(id){
                    $scope.a=id;
                }
            }
        };

    }).controller("ctrl",function($scope){
    $scope.abc="控制器上的数据"
})