angular.module("myapp",["ngRoute","ctrls","sevices"])
    .config(function($routeProvider){
        $routeProvider.when("/",{
            templateUrl:"indexcon.html",
            controller:"index"
        }).when("/list/:id",{
            templateUrl:"list.html",
            controller:"list"
        }).when("/show/:id",{
            templateUrl:"show.html",
            controller:"show"
        }).otherwise("/")
    })